name: Publish

#on:
#  push:
 #   tags:
 #     - '*'
 # workflow_dispatch:

on:
  release:
    types: [published]
    

permissions:
  contents: read
  id-token: write  # Required for OIDC authentication
    

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
      env:
        TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
